### ISSUE TITLE
Multiple nvme disks and resume from hibernate

### ISSUE THREAD

**Issue by Kirill888** [aws/ec2-hibernate-linux-agent#8]
I have hibernation/resuming working successfully with Ubuntu 18.04 based AMI on `c5.large` instance in `ap-southeast-2a` zone.

kernel:
```
Linux testbox 4.15.0-1043-aws #45-Ubuntu SMP Mon Jun 24 14:07:03 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

However if I attach a separate volume for `/home`  folder, then hibernate stops working reliably. This is because the device name for root vs home volumes changes between reboots, while `resume=/dev/nvme1n1p1` parameter is fixed to what was observed during hibernation.

Can resume use `UUID=` syntax instead of `/dev/...`?
Can kernel be told to assign `/dev/nvme` names consistently on boot for EBS volumes somehow?

**Comment by Kirill888** [comment]
I have confirmed that using `resume=UUID=".."` syntax works, at least with Ubuntu 18.04.

**Comment by einynot** [comment]
Hi, this has been added in "ubuntu" branch in commit https://github.com/aws/ec2-hibernate-linux-agent/commit/d83fa474aeaf5183b62e4c24ee16fdb46e74cff5
